# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.0.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
      docker:
        - image: circleci/postgres:9.6-alpine-ram
          environment:
            POSTGRES_USER: dbuser
            POSTGRES_DB: myRefriDB
        - image: circleci/node:10.6
          environment:
            PROFILE: test
            POSTGRES_URL: postgres://dbuser@localhost:5432/myRefriDB
            TZ: Europe/Berlin
      working_directory: ~/repo
      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

        - run: yarn install

        - attach_workspace:
            at: ~/repo
        - run:
            name: Wait for db
            command: dockerize -wait tcp://localhost:5432 -timeout 1m
        # run tests!
        - run:
            name: Run unit and integration test
            command: yarn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test