
const Item = require('../../model/Item');
// TODO: The list must be persisted in a DB, no in memory

class ItemHandler {
  constructor() {
    // TODO: Remove once the list is in the DB
    this.list = [];
  }

  getList() {
    return [...this.list];
  }

  findItemById(idItem) {
    const detailsItem = this.list.find(item => item.id === idItem);

    return detailsItem;
  }

  // TODO: The creation of the item should not require the id, because that is generated by the DB
  createNewItem(product, itemData) {
    const unity = itemData.unityItem;
    const quantity = itemData.quantityItem;
    const id = Math.random().toString(36).substring(2, 5);

    const newItem = new Item(id, product, Date(), unity, quantity, true);

    this.list.push(newItem);
    return newItem;
  }

  modifyItem(itemId, newQuantityItem, newUnityItem) {
    const indexModifiedItem = this.list.findIndex(previousItem => previousItem.id === itemId);

    this.list[indexModifiedItem].unityItem = newUnityItem;
    this.list[indexModifiedItem].quantityItem = newQuantityItem;
    return this.list[indexModifiedItem];
  }

  removeItemOfList(id) {
    const filterList = this.list.filter(item => item.id !== id);
    this.list = filterList;
  }
}

module.exports = ItemHandler;
